[package]
name = "sql_sanitizer"
version = "0.0.1"
edition = "2021"
authors = ["Andrew Hayworth <ahayworth@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.3", features = ["rb-sys-interop"] }
sql_lexer = "0.9"
